#!/usr/bin/env perl
use strict;
use File::Slurp;

our %PATH =
  ( 'keys' => './keys',
    'fdpe' => 'packages/apps/F-Droid/privileged-extension/app/src/main/java/org/fdroid/fdroid/privileged/ClientWhitelist.java'
  );

fatal("keys directory not found")
  unless (-d $PATH{keys});
fatal("ClientWhitelist.java not found")
  unless (-f $PATH{fdpe});

our @DEVICES = qw(bullhead angler sailfish marlin walleye taimen);
my $RAW_FDPE = read_file($PATH{fdpe});

foreach my $device (@DEVICES) {
  my $sig = get_fingerprint($device);
  stdout($sig." ".$device);
  $RAW_FDPE =~ s!^(\s*new Pair<>\(".+?", ").+?("\s*\),??\s*//\s*\Q$device\E releasekey)\s*$!${1}${sig}${2}!m;
}

write_file($PATH{fdpe},$RAW_FDPE);

chdir('packages/apps/F-Droid/privileged-extension/');
system('git diff');
exit 0;

sub get_fingerprint {
  my ($device) = @_;
  my $pem_path = $PATH{keys}.'/'.$device.'/releasekey.x509.pem';
  fatal("key net found: ".$pem_path)
    unless (-f $pem_path);
  my $result = `keytool -list -printcert -file "${pem_path}" 2>/dev/null | grep 'SHA256:' | tr -d ':' | cut -d ' ' -f 3`;
  chomp($result);
  return $result;
}

sub stdout {
  foreach (@_) {
    print STDOUT $_."\n";
  }
}
sub stderr {
  foreach (@_) {
    print STDERR $_."\n";
  }
}
sub fatal {
  stderr(@_);
  exit 1;
}
